server:
  port: 8006
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

  application:
    name: consul-provider-payment